import { Donation } from "@/components/molecules/settings-panel/my-donations-mock";

export const FOOD_TYPE_FILTERS = [
  { value: "all", label: "All Types" },
  { value: "Fresh Vegetables", label: "Fresh Vegetables" },
  { value: "Fresh Fruits", label: "Fresh Fruits" },
  { value: "Dairy Products", label: "Dairy Products" },
  { value: "Bread & Bakery", label: "Bread & Bakery" },
  { value: "Canned Goods", label: "Canned Goods" },
  { value: "Packaged Foods", label: "Packaged Foods" },
  { value: "Beverages", label: "Beverages" },
  { value: "Main Course", label: "Main Course" },
  { value: "Bakery Items", label: "Bakery Items" },
  { value: "Other", label: "Other" },
];

export const STATUS_FILTERS = [
  { value: "all", label: "All Status" },
  { value: "active", label: "Available" },
  { value: "claimed", label: "Claimed" },
  { value: "expired", label: "Expired" },
];

export const MOCK_AVAILABLE_DONATIONS: Donation[] = [
  {
    id: "browse-1",
    title: "Fresh Vegetables Bundle",
    description:
      "Mix of seasonal vegetables including carrots, lettuce, tomatoes, and bell peppers. Perfect for families looking for fresh produce.",
    foodType: "Fresh Vegetables",
    quantity: "5kg mixed vegetables",
    location: "Downtown Community Center",
    status: "active" as const,
    createdAt: "2025-08-03T10:00:00Z",
    expiresAt: "2025-08-10T18:00:00Z",
    availablePickupTimes: "9 AM - 5 PM",
    contactMethod: "email",
    email: "vegdonor@example.com",
    dietaryInfo: ["Vegan", "Gluten Free"],
    specialInstructions: "Please bring bags for carrying.",
    donorId: "donor-veg-1",
    receivers: null,
    isClaimed: false,
  },
  {
    id: "browse-2",
    title: "Homemade Lasagna - Family Size",
    description:
      "Delicious homemade lasagna with layers of pasta, meat sauce, and cheese. Enough to feed a family of 6. Made fresh today.",
    foodType: "Main Course",
    quantity: "2 large trays (6-8 servings)",
    location: "Riverside District Kitchen",
    status: "active" as const,
    createdAt: "2025-08-04T14:30:00Z",
    expiresAt: "2025-08-06T20:00:00Z",
    availablePickupTimes: "3 PM - 7 PM",
    contactMethod: "phone",
    phone: "+233501234569",
    dietaryInfo: ["Contains Dairy", "Contains Gluten"],
    specialInstructions: "Please bring large containers.",
    donorId: "donor-lasagna-1",
    receivers: null,
    isClaimed: false,
  },
  {
    id: "browse-3",
    title: "Fresh Cooked Rice and Beans",
    description: "A large pot of freshly cooked rice and beans available for donation.",
    foodType: "Canned Goods",
    quantity: "4 servings",
    location: "123 Community Lane, Accra",
    status: "active" as const,
    createdAt: "2025-08-04T18:01:36.179Z",
    expiresAt: "2025-08-05T08:00:00Z",
    availablePickupTimes: "9 AM - 12 PM",
    contactMethod: "email",
    email: "reactteamfour@gmail.com",
    phone: "+233501234567",
    dietaryInfo: ["Contains Nuts", "Contains Dairy"],
    specialInstructions: "Please bring your own container if possible.",
    donorId: "688bec21002459734fcf",
    receivers: null,
    isClaimed: false,
  },
  {
    id: "browse-4",
    title: "Bakery Surplus - Mixed Pastries",
    description:
      "Collection of fresh pastries from our bakery including croissants, muffins, and danish pastries. All made today.",
    foodType: "Bakery Items",
    quantity: "20 mixed pastries",
    location: "Golden Crust Bakery, East Accra",
    status: "active" as const,
    createdAt: "2025-08-04T07:00:00Z",
    expiresAt: "2025-08-05T19:00:00Z",
    availablePickupTimes: "7 AM - 7 PM",
    contactMethod: "both",
    phone: "+233501234570",
    email: "goldencrust@example.com",
    dietaryInfo: ["Contains Gluten", "Contains Dairy", "Contains Eggs"],
    specialInstructions: "Available at back entrance of bakery.",
    donorId: "donor-bakery-1",
    receivers: null,
    isClaimed: false,
  },
  {
    id: "browse-5",
    title: "Organic Chicken Stew",
    description:
      "Homemade organic chicken stew with vegetables and herbs. Perfect for families looking for a hearty meal.",
    foodType: "Main Course",
    quantity: "8 servings",
    location: "Organic Kitchen, Tema",
    status: "active" as const,
    createdAt: "2025-08-04T11:00:00Z",
    expiresAt: "2025-08-06T18:00:00Z",
    availablePickupTimes: "12 PM - 6 PM",
    contactMethod: "email",
    email: "organickitchen@example.com",
    dietaryInfo: ["Contains Meat", "Gluten Free"],
    specialInstructions: "Keep refrigerated. Reheat before serving.",
    donorId: "donor-organic-1",
    receivers: null,
    isClaimed: false,
  },
  {
    id: "browse-6",
    title: "Seasonal Fruit Box",
    description:
      "Fresh seasonal fruits including mangoes, oranges, bananas, and pineapples. All locally sourced and organic.",
    foodType: "Fresh Fruits",
    quantity: "5kg mixed fruits",
    location: "Fresh Market, Cape Coast",
    status: "active" as const,
    createdAt: "2025-08-03T16:00:00Z",
    expiresAt: "2025-08-08T20:00:00Z",
    availablePickupTimes: "8 AM - 6 PM",
    contactMethod: "phone",
    phone: "+233501234571",
    dietaryInfo: ["Vegan", "Raw", "Gluten Free"],
    specialInstructions: "Best consumed within 3 days.",
    donorId: "donor-fruits-1",
    receivers: null,
    isClaimed: false,
  },
];
